### ISSUE TITLE
No stack. program is not being run.

### ISSUE THREAD

**Issue by SilentAutomaton** [ejones/llama-journey#4]
![2023-12-09_16-23](https://github.com/ejones/llama-journey/assets/36517882/93431f3c-cfbb-486a-a575-72385495ee00)
This is a consistent issue with every Llama model I tried. Dialogue starts on top of map and returns an error. Either "program is not being run" or wrong Llama output format.
On the screenshot I was using standart Llama2-13B (Q4K_S not M like in your tests).
System is arch linux. 
Gpu is rtx2070 max-q (laptop one, 8GB vram)
Llama.cpp is compiled with cuda support and laptop is capable of running 13B version of Llama separately from game.

Cool project btw. Surprised nobody tried to do this before

**Comment by ejones** [comment]
Thanks for the detailed report! By any chance are you using a recent llama.cpp build? Looking at [#4376](https://github.com/ggerganov/llama.cpp/issues/4376) I'm wondering if this was a recent regression in llama grammars. If so, do you mind recompiling the latest llama.cpp? I can more or less reproduce your issue with `HEAD^` and it appears to be fixed in the latest.

**Comment by SilentAutomaton** [comment]
Yeah it works now, but bartender always give me money instead of taking them and never gives anything else. ![2023-12-20_05-15](https://github.com/ejones/llama-journey/assets/36517882/1d1afd50-d34d-4323-8d2f-55023f79903e)
![2023-12-20_05-13_1](https://github.com/ejones/llama-journey/assets/36517882/d129fa4d-955e-4d80-82e7-ffd45cf4717f)

Btw i experemented with llama.cpp a little bit and I believe that your project lacks an option to load model layers in vram that probably makes it slower and less smart. 
llama.cpp uses flag "-ngl <layer_numbers>" for this and adding an option to passthrough it can be a good addition.

**Comment by ejones** [comment]
Good to hear it's working!

> bartender always give me money instead of taking them

Yeah it's hit or miss for me as well, at least at 13B. The approach here gives the model the flexibility on the outcome, rather than mandating that, say, giving always results in a deduction or that you're guaranteed to receive something. In particular the inventory change mechanic takes an int delta, and the initial prompt (prompt.txt) probably doesn't establish well enough that it can be negative.

> I believe that your project lacks an option to load model layers in vram

Yeah I think it just needs a generic passthrough of llama.cpp options. I sort of optimized for the Mac experience, where the defaults now are pretty sensible.
